use_frameworks!

platform :ios, '12.0'

target 'KhaltiCheckout_Example' do
  pod 'KhaltiCheckout', :path => '../'

  target 'KhaltiCheckout_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
